# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xchy/Projects/de3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xchy/Projects/de3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xchy/Projects/de3/CMakeFiles /home/xchy/Projects/de3//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xchy/Projects/de3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named omp_gen

# Build rule for target.
omp_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 omp_gen
.PHONY : omp_gen

# fast build rule for target.
omp_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omp_gen.dir/build.make CMakeFiles/omp_gen.dir/build
.PHONY : omp_gen/fast

#=============================================================================
# Target rules for targets named acc_gen

# Build rule for target.
acc_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acc_gen
.PHONY : acc_gen

# fast build rule for target.
acc_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acc_gen.dir/build.make CMakeFiles/acc_gen.dir/build
.PHONY : acc_gen/fast

#=============================================================================
# Target rules for targets named RISCVTargetParserTableGen

# Build rule for target.
RISCVTargetParserTableGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RISCVTargetParserTableGen
.PHONY : RISCVTargetParserTableGen

# fast build rule for target.
RISCVTargetParserTableGen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RISCVTargetParserTableGen.dir/build.make CMakeFiles/RISCVTargetParserTableGen.dir/build
.PHONY : RISCVTargetParserTableGen/fast

#=============================================================================
# Target rules for targets named UnoptGenCore

# Build rule for target.
UnoptGenCore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UnoptGenCore
.PHONY : UnoptGenCore

# fast build rule for target.
UnoptGenCore/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/build
.PHONY : UnoptGenCore/fast

#=============================================================================
# Target rules for targets named deoptgen

# Build rule for target.
deoptgen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 deoptgen
.PHONY : deoptgen

# fast build rule for target.
deoptgen/fast:
	$(MAKE) $(MAKESILENT) -f src/tools/deoptgen/CMakeFiles/deoptgen.dir/build.make src/tools/deoptgen/CMakeFiles/deoptgen.dir/build
.PHONY : deoptgen/fast

#=============================================================================
# Target rules for targets named moclassify

# Build rule for target.
moclassify: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 moclassify
.PHONY : moclassify

# fast build rule for target.
moclassify/fast:
	$(MAKE) $(MAKESILENT) -f src/tools/moclassify/CMakeFiles/moclassify.dir/build.make src/tools/moclassify/CMakeFiles/moclassify.dir/build
.PHONY : moclassify/fast

#=============================================================================
# Target rules for targets named mochecker

# Build rule for target.
mochecker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mochecker
.PHONY : mochecker

# fast build rule for target.
mochecker/fast:
	$(MAKE) $(MAKESILENT) -f src/tools/mochecker/CMakeFiles/mochecker.dir/build.make src/tools/mochecker/CMakeFiles/mochecker.dir/build
.PHONY : mochecker/fast

#=============================================================================
# Target rules for targets named mo-diff

# Build rule for target.
mo-diff: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mo-diff
.PHONY : mo-diff

# fast build rule for target.
mo-diff/fast:
	$(MAKE) $(MAKESILENT) -f src/tools/mo-diff/CMakeFiles/mo-diff.dir/build.make src/tools/mo-diff/CMakeFiles/mo-diff.dir/build
.PHONY : mo-diff/fast

src/indicators/DiffChecker.o: src/indicators/DiffChecker.cpp.o
.PHONY : src/indicators/DiffChecker.o

# target to build an object file
src/indicators/DiffChecker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/indicators/DiffChecker.cpp.o
.PHONY : src/indicators/DiffChecker.cpp.o

src/indicators/DiffChecker.i: src/indicators/DiffChecker.cpp.i
.PHONY : src/indicators/DiffChecker.i

# target to preprocess a source file
src/indicators/DiffChecker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/indicators/DiffChecker.cpp.i
.PHONY : src/indicators/DiffChecker.cpp.i

src/indicators/DiffChecker.s: src/indicators/DiffChecker.cpp.s
.PHONY : src/indicators/DiffChecker.s

# target to generate assembly for a file
src/indicators/DiffChecker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/indicators/DiffChecker.cpp.s
.PHONY : src/indicators/DiffChecker.cpp.s

src/indicators/InlineIndicator.o: src/indicators/InlineIndicator.cpp.o
.PHONY : src/indicators/InlineIndicator.o

# target to build an object file
src/indicators/InlineIndicator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/indicators/InlineIndicator.cpp.o
.PHONY : src/indicators/InlineIndicator.cpp.o

src/indicators/InlineIndicator.i: src/indicators/InlineIndicator.cpp.i
.PHONY : src/indicators/InlineIndicator.i

# target to preprocess a source file
src/indicators/InlineIndicator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/indicators/InlineIndicator.cpp.i
.PHONY : src/indicators/InlineIndicator.cpp.i

src/indicators/InlineIndicator.s: src/indicators/InlineIndicator.cpp.s
.PHONY : src/indicators/InlineIndicator.s

# target to generate assembly for a file
src/indicators/InlineIndicator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/indicators/InlineIndicator.cpp.s
.PHONY : src/indicators/InlineIndicator.cpp.s

src/indicators/InstCountIndicator.o: src/indicators/InstCountIndicator.cpp.o
.PHONY : src/indicators/InstCountIndicator.o

# target to build an object file
src/indicators/InstCountIndicator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/indicators/InstCountIndicator.cpp.o
.PHONY : src/indicators/InstCountIndicator.cpp.o

src/indicators/InstCountIndicator.i: src/indicators/InstCountIndicator.cpp.i
.PHONY : src/indicators/InstCountIndicator.i

# target to preprocess a source file
src/indicators/InstCountIndicator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/indicators/InstCountIndicator.cpp.i
.PHONY : src/indicators/InstCountIndicator.cpp.i

src/indicators/InstCountIndicator.s: src/indicators/InstCountIndicator.cpp.s
.PHONY : src/indicators/InstCountIndicator.s

# target to generate assembly for a file
src/indicators/InstCountIndicator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/indicators/InstCountIndicator.cpp.s
.PHONY : src/indicators/InstCountIndicator.cpp.s

src/indicators/LoopIndicator.o: src/indicators/LoopIndicator.cpp.o
.PHONY : src/indicators/LoopIndicator.o

# target to build an object file
src/indicators/LoopIndicator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/indicators/LoopIndicator.cpp.o
.PHONY : src/indicators/LoopIndicator.cpp.o

src/indicators/LoopIndicator.i: src/indicators/LoopIndicator.cpp.i
.PHONY : src/indicators/LoopIndicator.i

# target to preprocess a source file
src/indicators/LoopIndicator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/indicators/LoopIndicator.cpp.i
.PHONY : src/indicators/LoopIndicator.cpp.i

src/indicators/LoopIndicator.s: src/indicators/LoopIndicator.cpp.s
.PHONY : src/indicators/LoopIndicator.s

# target to generate assembly for a file
src/indicators/LoopIndicator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/indicators/LoopIndicator.cpp.s
.PHONY : src/indicators/LoopIndicator.cpp.s

src/indicators/StaticProfileIndicator.o: src/indicators/StaticProfileIndicator.cpp.o
.PHONY : src/indicators/StaticProfileIndicator.o

# target to build an object file
src/indicators/StaticProfileIndicator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/indicators/StaticProfileIndicator.cpp.o
.PHONY : src/indicators/StaticProfileIndicator.cpp.o

src/indicators/StaticProfileIndicator.i: src/indicators/StaticProfileIndicator.cpp.i
.PHONY : src/indicators/StaticProfileIndicator.i

# target to preprocess a source file
src/indicators/StaticProfileIndicator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/indicators/StaticProfileIndicator.cpp.i
.PHONY : src/indicators/StaticProfileIndicator.cpp.i

src/indicators/StaticProfileIndicator.s: src/indicators/StaticProfileIndicator.cpp.s
.PHONY : src/indicators/StaticProfileIndicator.s

# target to generate assembly for a file
src/indicators/StaticProfileIndicator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/indicators/StaticProfileIndicator.cpp.s
.PHONY : src/indicators/StaticProfileIndicator.cpp.s

src/indicators/UBChecker.o: src/indicators/UBChecker.cpp.o
.PHONY : src/indicators/UBChecker.o

# target to build an object file
src/indicators/UBChecker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/indicators/UBChecker.cpp.o
.PHONY : src/indicators/UBChecker.cpp.o

src/indicators/UBChecker.i: src/indicators/UBChecker.cpp.i
.PHONY : src/indicators/UBChecker.i

# target to preprocess a source file
src/indicators/UBChecker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/indicators/UBChecker.cpp.i
.PHONY : src/indicators/UBChecker.cpp.i

src/indicators/UBChecker.s: src/indicators/UBChecker.cpp.s
.PHONY : src/indicators/UBChecker.s

# target to generate assembly for a file
src/indicators/UBChecker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/indicators/UBChecker.cpp.s
.PHONY : src/indicators/UBChecker.cpp.s

src/transforms/CFGExpand/CFGExpand.o: src/transforms/CFGExpand/CFGExpand.cpp.o
.PHONY : src/transforms/CFGExpand/CFGExpand.o

# target to build an object file
src/transforms/CFGExpand/CFGExpand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/CFGExpand/CFGExpand.cpp.o
.PHONY : src/transforms/CFGExpand/CFGExpand.cpp.o

src/transforms/CFGExpand/CFGExpand.i: src/transforms/CFGExpand/CFGExpand.cpp.i
.PHONY : src/transforms/CFGExpand/CFGExpand.i

# target to preprocess a source file
src/transforms/CFGExpand/CFGExpand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/CFGExpand/CFGExpand.cpp.i
.PHONY : src/transforms/CFGExpand/CFGExpand.cpp.i

src/transforms/CFGExpand/CFGExpand.s: src/transforms/CFGExpand/CFGExpand.cpp.s
.PHONY : src/transforms/CFGExpand/CFGExpand.s

# target to generate assembly for a file
src/transforms/CFGExpand/CFGExpand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/CFGExpand/CFGExpand.cpp.s
.PHONY : src/transforms/CFGExpand/CFGExpand.cpp.s

src/transforms/CFGExpand/CFGExpander.o: src/transforms/CFGExpand/CFGExpander.cpp.o
.PHONY : src/transforms/CFGExpand/CFGExpander.o

# target to build an object file
src/transforms/CFGExpand/CFGExpander.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/CFGExpand/CFGExpander.cpp.o
.PHONY : src/transforms/CFGExpand/CFGExpander.cpp.o

src/transforms/CFGExpand/CFGExpander.i: src/transforms/CFGExpand/CFGExpander.cpp.i
.PHONY : src/transforms/CFGExpand/CFGExpander.i

# target to preprocess a source file
src/transforms/CFGExpand/CFGExpander.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/CFGExpand/CFGExpander.cpp.i
.PHONY : src/transforms/CFGExpand/CFGExpander.cpp.i

src/transforms/CFGExpand/CFGExpander.s: src/transforms/CFGExpand/CFGExpander.cpp.s
.PHONY : src/transforms/CFGExpand/CFGExpander.s

# target to generate assembly for a file
src/transforms/CFGExpand/CFGExpander.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/CFGExpand/CFGExpander.cpp.s
.PHONY : src/transforms/CFGExpand/CFGExpander.cpp.s

src/transforms/CFGRandomSimplify/CFGRandomSimplify.o: src/transforms/CFGRandomSimplify/CFGRandomSimplify.cpp.o
.PHONY : src/transforms/CFGRandomSimplify/CFGRandomSimplify.o

# target to build an object file
src/transforms/CFGRandomSimplify/CFGRandomSimplify.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/CFGRandomSimplify/CFGRandomSimplify.cpp.o
.PHONY : src/transforms/CFGRandomSimplify/CFGRandomSimplify.cpp.o

src/transforms/CFGRandomSimplify/CFGRandomSimplify.i: src/transforms/CFGRandomSimplify/CFGRandomSimplify.cpp.i
.PHONY : src/transforms/CFGRandomSimplify/CFGRandomSimplify.i

# target to preprocess a source file
src/transforms/CFGRandomSimplify/CFGRandomSimplify.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/CFGRandomSimplify/CFGRandomSimplify.cpp.i
.PHONY : src/transforms/CFGRandomSimplify/CFGRandomSimplify.cpp.i

src/transforms/CFGRandomSimplify/CFGRandomSimplify.s: src/transforms/CFGRandomSimplify/CFGRandomSimplify.cpp.s
.PHONY : src/transforms/CFGRandomSimplify/CFGRandomSimplify.s

# target to generate assembly for a file
src/transforms/CFGRandomSimplify/CFGRandomSimplify.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/CFGRandomSimplify/CFGRandomSimplify.cpp.s
.PHONY : src/transforms/CFGRandomSimplify/CFGRandomSimplify.cpp.s

src/transforms/ExprExpand/AddSubExpand.o: src/transforms/ExprExpand/AddSubExpand.cpp.o
.PHONY : src/transforms/ExprExpand/AddSubExpand.o

# target to build an object file
src/transforms/ExprExpand/AddSubExpand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/AddSubExpand.cpp.o
.PHONY : src/transforms/ExprExpand/AddSubExpand.cpp.o

src/transforms/ExprExpand/AddSubExpand.i: src/transforms/ExprExpand/AddSubExpand.cpp.i
.PHONY : src/transforms/ExprExpand/AddSubExpand.i

# target to preprocess a source file
src/transforms/ExprExpand/AddSubExpand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/AddSubExpand.cpp.i
.PHONY : src/transforms/ExprExpand/AddSubExpand.cpp.i

src/transforms/ExprExpand/AddSubExpand.s: src/transforms/ExprExpand/AddSubExpand.cpp.s
.PHONY : src/transforms/ExprExpand/AddSubExpand.s

# target to generate assembly for a file
src/transforms/ExprExpand/AddSubExpand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/AddSubExpand.cpp.s
.PHONY : src/transforms/ExprExpand/AddSubExpand.cpp.s

src/transforms/ExprExpand/BitwiseExpand.o: src/transforms/ExprExpand/BitwiseExpand.cpp.o
.PHONY : src/transforms/ExprExpand/BitwiseExpand.o

# target to build an object file
src/transforms/ExprExpand/BitwiseExpand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/BitwiseExpand.cpp.o
.PHONY : src/transforms/ExprExpand/BitwiseExpand.cpp.o

src/transforms/ExprExpand/BitwiseExpand.i: src/transforms/ExprExpand/BitwiseExpand.cpp.i
.PHONY : src/transforms/ExprExpand/BitwiseExpand.i

# target to preprocess a source file
src/transforms/ExprExpand/BitwiseExpand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/BitwiseExpand.cpp.i
.PHONY : src/transforms/ExprExpand/BitwiseExpand.cpp.i

src/transforms/ExprExpand/BitwiseExpand.s: src/transforms/ExprExpand/BitwiseExpand.cpp.s
.PHONY : src/transforms/ExprExpand/BitwiseExpand.s

# target to generate assembly for a file
src/transforms/ExprExpand/BitwiseExpand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/BitwiseExpand.cpp.s
.PHONY : src/transforms/ExprExpand/BitwiseExpand.cpp.s

src/transforms/ExprExpand/ExprExpandPass.o: src/transforms/ExprExpand/ExprExpandPass.cpp.o
.PHONY : src/transforms/ExprExpand/ExprExpandPass.o

# target to build an object file
src/transforms/ExprExpand/ExprExpandPass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/ExprExpandPass.cpp.o
.PHONY : src/transforms/ExprExpand/ExprExpandPass.cpp.o

src/transforms/ExprExpand/ExprExpandPass.i: src/transforms/ExprExpand/ExprExpandPass.cpp.i
.PHONY : src/transforms/ExprExpand/ExprExpandPass.i

# target to preprocess a source file
src/transforms/ExprExpand/ExprExpandPass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/ExprExpandPass.cpp.i
.PHONY : src/transforms/ExprExpand/ExprExpandPass.cpp.i

src/transforms/ExprExpand/ExprExpandPass.s: src/transforms/ExprExpand/ExprExpandPass.cpp.s
.PHONY : src/transforms/ExprExpand/ExprExpandPass.s

# target to generate assembly for a file
src/transforms/ExprExpand/ExprExpandPass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/ExprExpandPass.cpp.s
.PHONY : src/transforms/ExprExpand/ExprExpandPass.cpp.s

src/transforms/ExprExpand/ExprExpander.o: src/transforms/ExprExpand/ExprExpander.cpp.o
.PHONY : src/transforms/ExprExpand/ExprExpander.o

# target to build an object file
src/transforms/ExprExpand/ExprExpander.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/ExprExpander.cpp.o
.PHONY : src/transforms/ExprExpand/ExprExpander.cpp.o

src/transforms/ExprExpand/ExprExpander.i: src/transforms/ExprExpand/ExprExpander.cpp.i
.PHONY : src/transforms/ExprExpand/ExprExpander.i

# target to preprocess a source file
src/transforms/ExprExpand/ExprExpander.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/ExprExpander.cpp.i
.PHONY : src/transforms/ExprExpand/ExprExpander.cpp.i

src/transforms/ExprExpand/ExprExpander.s: src/transforms/ExprExpand/ExprExpander.cpp.s
.PHONY : src/transforms/ExprExpand/ExprExpander.s

# target to generate assembly for a file
src/transforms/ExprExpand/ExprExpander.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/ExprExpander.cpp.s
.PHONY : src/transforms/ExprExpand/ExprExpander.cpp.s

src/transforms/ExprExpand/ICmpExpander.o: src/transforms/ExprExpand/ICmpExpander.cpp.o
.PHONY : src/transforms/ExprExpand/ICmpExpander.o

# target to build an object file
src/transforms/ExprExpand/ICmpExpander.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/ICmpExpander.cpp.o
.PHONY : src/transforms/ExprExpand/ICmpExpander.cpp.o

src/transforms/ExprExpand/ICmpExpander.i: src/transforms/ExprExpand/ICmpExpander.cpp.i
.PHONY : src/transforms/ExprExpand/ICmpExpander.i

# target to preprocess a source file
src/transforms/ExprExpand/ICmpExpander.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/ICmpExpander.cpp.i
.PHONY : src/transforms/ExprExpand/ICmpExpander.cpp.i

src/transforms/ExprExpand/ICmpExpander.s: src/transforms/ExprExpand/ICmpExpander.cpp.s
.PHONY : src/transforms/ExprExpand/ICmpExpander.s

# target to generate assembly for a file
src/transforms/ExprExpand/ICmpExpander.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/ICmpExpander.cpp.s
.PHONY : src/transforms/ExprExpand/ICmpExpander.cpp.s

src/transforms/ExprExpand/InstExpander.o: src/transforms/ExprExpand/InstExpander.cpp.o
.PHONY : src/transforms/ExprExpand/InstExpander.o

# target to build an object file
src/transforms/ExprExpand/InstExpander.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/InstExpander.cpp.o
.PHONY : src/transforms/ExprExpand/InstExpander.cpp.o

src/transforms/ExprExpand/InstExpander.i: src/transforms/ExprExpand/InstExpander.cpp.i
.PHONY : src/transforms/ExprExpand/InstExpander.i

# target to preprocess a source file
src/transforms/ExprExpand/InstExpander.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/InstExpander.cpp.i
.PHONY : src/transforms/ExprExpand/InstExpander.cpp.i

src/transforms/ExprExpand/InstExpander.s: src/transforms/ExprExpand/InstExpander.cpp.s
.PHONY : src/transforms/ExprExpand/InstExpander.s

# target to generate assembly for a file
src/transforms/ExprExpand/InstExpander.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/InstExpander.cpp.s
.PHONY : src/transforms/ExprExpand/InstExpander.cpp.s

src/transforms/ExprExpand/MulDivRemExpander.o: src/transforms/ExprExpand/MulDivRemExpander.cpp.o
.PHONY : src/transforms/ExprExpand/MulDivRemExpander.o

# target to build an object file
src/transforms/ExprExpand/MulDivRemExpander.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/MulDivRemExpander.cpp.o
.PHONY : src/transforms/ExprExpand/MulDivRemExpander.cpp.o

src/transforms/ExprExpand/MulDivRemExpander.i: src/transforms/ExprExpand/MulDivRemExpander.cpp.i
.PHONY : src/transforms/ExprExpand/MulDivRemExpander.i

# target to preprocess a source file
src/transforms/ExprExpand/MulDivRemExpander.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/MulDivRemExpander.cpp.i
.PHONY : src/transforms/ExprExpand/MulDivRemExpander.cpp.i

src/transforms/ExprExpand/MulDivRemExpander.s: src/transforms/ExprExpand/MulDivRemExpander.cpp.s
.PHONY : src/transforms/ExprExpand/MulDivRemExpander.s

# target to generate assembly for a file
src/transforms/ExprExpand/MulDivRemExpander.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/MulDivRemExpander.cpp.s
.PHONY : src/transforms/ExprExpand/MulDivRemExpander.cpp.s

src/transforms/ExprExpand/ShiftExpand.o: src/transforms/ExprExpand/ShiftExpand.cpp.o
.PHONY : src/transforms/ExprExpand/ShiftExpand.o

# target to build an object file
src/transforms/ExprExpand/ShiftExpand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/ShiftExpand.cpp.o
.PHONY : src/transforms/ExprExpand/ShiftExpand.cpp.o

src/transforms/ExprExpand/ShiftExpand.i: src/transforms/ExprExpand/ShiftExpand.cpp.i
.PHONY : src/transforms/ExprExpand/ShiftExpand.i

# target to preprocess a source file
src/transforms/ExprExpand/ShiftExpand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/ShiftExpand.cpp.i
.PHONY : src/transforms/ExprExpand/ShiftExpand.cpp.i

src/transforms/ExprExpand/ShiftExpand.s: src/transforms/ExprExpand/ShiftExpand.cpp.s
.PHONY : src/transforms/ExprExpand/ShiftExpand.s

# target to generate assembly for a file
src/transforms/ExprExpand/ShiftExpand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/ExprExpand/ShiftExpand.cpp.s
.PHONY : src/transforms/ExprExpand/ShiftExpand.cpp.s

src/transforms/InstRandomCombine/InstRandomCombine.o: src/transforms/InstRandomCombine/InstRandomCombine.cpp.o
.PHONY : src/transforms/InstRandomCombine/InstRandomCombine.o

# target to build an object file
src/transforms/InstRandomCombine/InstRandomCombine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/InstRandomCombine/InstRandomCombine.cpp.o
.PHONY : src/transforms/InstRandomCombine/InstRandomCombine.cpp.o

src/transforms/InstRandomCombine/InstRandomCombine.i: src/transforms/InstRandomCombine/InstRandomCombine.cpp.i
.PHONY : src/transforms/InstRandomCombine/InstRandomCombine.i

# target to preprocess a source file
src/transforms/InstRandomCombine/InstRandomCombine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/InstRandomCombine/InstRandomCombine.cpp.i
.PHONY : src/transforms/InstRandomCombine/InstRandomCombine.cpp.i

src/transforms/InstRandomCombine/InstRandomCombine.s: src/transforms/InstRandomCombine/InstRandomCombine.cpp.s
.PHONY : src/transforms/InstRandomCombine/InstRandomCombine.s

# target to generate assembly for a file
src/transforms/InstRandomCombine/InstRandomCombine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/InstRandomCombine/InstRandomCombine.cpp.s
.PHONY : src/transforms/InstRandomCombine/InstRandomCombine.cpp.s

src/transforms/RandomCVP/RandomCVP.o: src/transforms/RandomCVP/RandomCVP.cpp.o
.PHONY : src/transforms/RandomCVP/RandomCVP.o

# target to build an object file
src/transforms/RandomCVP/RandomCVP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomCVP/RandomCVP.cpp.o
.PHONY : src/transforms/RandomCVP/RandomCVP.cpp.o

src/transforms/RandomCVP/RandomCVP.i: src/transforms/RandomCVP/RandomCVP.cpp.i
.PHONY : src/transforms/RandomCVP/RandomCVP.i

# target to preprocess a source file
src/transforms/RandomCVP/RandomCVP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomCVP/RandomCVP.cpp.i
.PHONY : src/transforms/RandomCVP/RandomCVP.cpp.i

src/transforms/RandomCVP/RandomCVP.s: src/transforms/RandomCVP/RandomCVP.cpp.s
.PHONY : src/transforms/RandomCVP/RandomCVP.s

# target to generate assembly for a file
src/transforms/RandomCVP/RandomCVP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomCVP/RandomCVP.cpp.s
.PHONY : src/transforms/RandomCVP/RandomCVP.cpp.s

src/transforms/RandomDSE/RandomDSE.o: src/transforms/RandomDSE/RandomDSE.cpp.o
.PHONY : src/transforms/RandomDSE/RandomDSE.o

# target to build an object file
src/transforms/RandomDSE/RandomDSE.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomDSE/RandomDSE.cpp.o
.PHONY : src/transforms/RandomDSE/RandomDSE.cpp.o

src/transforms/RandomDSE/RandomDSE.i: src/transforms/RandomDSE/RandomDSE.cpp.i
.PHONY : src/transforms/RandomDSE/RandomDSE.i

# target to preprocess a source file
src/transforms/RandomDSE/RandomDSE.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomDSE/RandomDSE.cpp.i
.PHONY : src/transforms/RandomDSE/RandomDSE.cpp.i

src/transforms/RandomDSE/RandomDSE.s: src/transforms/RandomDSE/RandomDSE.cpp.s
.PHONY : src/transforms/RandomDSE/RandomDSE.s

# target to generate assembly for a file
src/transforms/RandomDSE/RandomDSE.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomDSE/RandomDSE.cpp.s
.PHONY : src/transforms/RandomDSE/RandomDSE.cpp.s

src/transforms/RandomLICM/RandomLICM.o: src/transforms/RandomLICM/RandomLICM.cpp.o
.PHONY : src/transforms/RandomLICM/RandomLICM.o

# target to build an object file
src/transforms/RandomLICM/RandomLICM.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomLICM/RandomLICM.cpp.o
.PHONY : src/transforms/RandomLICM/RandomLICM.cpp.o

src/transforms/RandomLICM/RandomLICM.i: src/transforms/RandomLICM/RandomLICM.cpp.i
.PHONY : src/transforms/RandomLICM/RandomLICM.i

# target to preprocess a source file
src/transforms/RandomLICM/RandomLICM.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomLICM/RandomLICM.cpp.i
.PHONY : src/transforms/RandomLICM/RandomLICM.cpp.i

src/transforms/RandomLICM/RandomLICM.s: src/transforms/RandomLICM/RandomLICM.cpp.s
.PHONY : src/transforms/RandomLICM/RandomLICM.s

# target to generate assembly for a file
src/transforms/RandomLICM/RandomLICM.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomLICM/RandomLICM.cpp.s
.PHONY : src/transforms/RandomLICM/RandomLICM.cpp.s

src/transforms/RandomLoopSink/RandomLoopSink.o: src/transforms/RandomLoopSink/RandomLoopSink.cpp.o
.PHONY : src/transforms/RandomLoopSink/RandomLoopSink.o

# target to build an object file
src/transforms/RandomLoopSink/RandomLoopSink.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomLoopSink/RandomLoopSink.cpp.o
.PHONY : src/transforms/RandomLoopSink/RandomLoopSink.cpp.o

src/transforms/RandomLoopSink/RandomLoopSink.i: src/transforms/RandomLoopSink/RandomLoopSink.cpp.i
.PHONY : src/transforms/RandomLoopSink/RandomLoopSink.i

# target to preprocess a source file
src/transforms/RandomLoopSink/RandomLoopSink.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomLoopSink/RandomLoopSink.cpp.i
.PHONY : src/transforms/RandomLoopSink/RandomLoopSink.cpp.i

src/transforms/RandomLoopSink/RandomLoopSink.s: src/transforms/RandomLoopSink/RandomLoopSink.cpp.s
.PHONY : src/transforms/RandomLoopSink/RandomLoopSink.s

# target to generate assembly for a file
src/transforms/RandomLoopSink/RandomLoopSink.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomLoopSink/RandomLoopSink.cpp.s
.PHONY : src/transforms/RandomLoopSink/RandomLoopSink.cpp.s

src/transforms/RandomMem2Reg/RandomMem2Reg.o: src/transforms/RandomMem2Reg/RandomMem2Reg.cpp.o
.PHONY : src/transforms/RandomMem2Reg/RandomMem2Reg.o

# target to build an object file
src/transforms/RandomMem2Reg/RandomMem2Reg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomMem2Reg/RandomMem2Reg.cpp.o
.PHONY : src/transforms/RandomMem2Reg/RandomMem2Reg.cpp.o

src/transforms/RandomMem2Reg/RandomMem2Reg.i: src/transforms/RandomMem2Reg/RandomMem2Reg.cpp.i
.PHONY : src/transforms/RandomMem2Reg/RandomMem2Reg.i

# target to preprocess a source file
src/transforms/RandomMem2Reg/RandomMem2Reg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomMem2Reg/RandomMem2Reg.cpp.i
.PHONY : src/transforms/RandomMem2Reg/RandomMem2Reg.cpp.i

src/transforms/RandomMem2Reg/RandomMem2Reg.s: src/transforms/RandomMem2Reg/RandomMem2Reg.cpp.s
.PHONY : src/transforms/RandomMem2Reg/RandomMem2Reg.s

# target to generate assembly for a file
src/transforms/RandomMem2Reg/RandomMem2Reg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomMem2Reg/RandomMem2Reg.cpp.s
.PHONY : src/transforms/RandomMem2Reg/RandomMem2Reg.cpp.s

src/transforms/RandomReg2Mem/RandomReg2Mem.o: src/transforms/RandomReg2Mem/RandomReg2Mem.cpp.o
.PHONY : src/transforms/RandomReg2Mem/RandomReg2Mem.o

# target to build an object file
src/transforms/RandomReg2Mem/RandomReg2Mem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomReg2Mem/RandomReg2Mem.cpp.o
.PHONY : src/transforms/RandomReg2Mem/RandomReg2Mem.cpp.o

src/transforms/RandomReg2Mem/RandomReg2Mem.i: src/transforms/RandomReg2Mem/RandomReg2Mem.cpp.i
.PHONY : src/transforms/RandomReg2Mem/RandomReg2Mem.i

# target to preprocess a source file
src/transforms/RandomReg2Mem/RandomReg2Mem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomReg2Mem/RandomReg2Mem.cpp.i
.PHONY : src/transforms/RandomReg2Mem/RandomReg2Mem.cpp.i

src/transforms/RandomReg2Mem/RandomReg2Mem.s: src/transforms/RandomReg2Mem/RandomReg2Mem.cpp.s
.PHONY : src/transforms/RandomReg2Mem/RandomReg2Mem.s

# target to generate assembly for a file
src/transforms/RandomReg2Mem/RandomReg2Mem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomReg2Mem/RandomReg2Mem.cpp.s
.PHONY : src/transforms/RandomReg2Mem/RandomReg2Mem.cpp.s

src/transforms/RandomScalarizer/RandomScalarizer.o: src/transforms/RandomScalarizer/RandomScalarizer.cpp.o
.PHONY : src/transforms/RandomScalarizer/RandomScalarizer.o

# target to build an object file
src/transforms/RandomScalarizer/RandomScalarizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomScalarizer/RandomScalarizer.cpp.o
.PHONY : src/transforms/RandomScalarizer/RandomScalarizer.cpp.o

src/transforms/RandomScalarizer/RandomScalarizer.i: src/transforms/RandomScalarizer/RandomScalarizer.cpp.i
.PHONY : src/transforms/RandomScalarizer/RandomScalarizer.i

# target to preprocess a source file
src/transforms/RandomScalarizer/RandomScalarizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomScalarizer/RandomScalarizer.cpp.i
.PHONY : src/transforms/RandomScalarizer/RandomScalarizer.cpp.i

src/transforms/RandomScalarizer/RandomScalarizer.s: src/transforms/RandomScalarizer/RandomScalarizer.cpp.s
.PHONY : src/transforms/RandomScalarizer/RandomScalarizer.s

# target to generate assembly for a file
src/transforms/RandomScalarizer/RandomScalarizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomScalarizer/RandomScalarizer.cpp.s
.PHONY : src/transforms/RandomScalarizer/RandomScalarizer.cpp.s

src/transforms/RandomSink/RandomSink.o: src/transforms/RandomSink/RandomSink.cpp.o
.PHONY : src/transforms/RandomSink/RandomSink.o

# target to build an object file
src/transforms/RandomSink/RandomSink.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomSink/RandomSink.cpp.o
.PHONY : src/transforms/RandomSink/RandomSink.cpp.o

src/transforms/RandomSink/RandomSink.i: src/transforms/RandomSink/RandomSink.cpp.i
.PHONY : src/transforms/RandomSink/RandomSink.i

# target to preprocess a source file
src/transforms/RandomSink/RandomSink.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomSink/RandomSink.cpp.i
.PHONY : src/transforms/RandomSink/RandomSink.cpp.i

src/transforms/RandomSink/RandomSink.s: src/transforms/RandomSink/RandomSink.cpp.s
.PHONY : src/transforms/RandomSink/RandomSink.s

# target to generate assembly for a file
src/transforms/RandomSink/RandomSink.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/transforms/RandomSink/RandomSink.cpp.s
.PHONY : src/transforms/RandomSink/RandomSink.cpp.s

src/utils/Debug.o: src/utils/Debug.cpp.o
.PHONY : src/utils/Debug.o

# target to build an object file
src/utils/Debug.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/utils/Debug.cpp.o
.PHONY : src/utils/Debug.cpp.o

src/utils/Debug.i: src/utils/Debug.cpp.i
.PHONY : src/utils/Debug.i

# target to preprocess a source file
src/utils/Debug.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/utils/Debug.cpp.i
.PHONY : src/utils/Debug.cpp.i

src/utils/Debug.s: src/utils/Debug.cpp.s
.PHONY : src/utils/Debug.s

# target to generate assembly for a file
src/utils/Debug.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/utils/Debug.cpp.s
.PHONY : src/utils/Debug.cpp.s

src/utils/Files.o: src/utils/Files.cpp.o
.PHONY : src/utils/Files.o

# target to build an object file
src/utils/Files.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/utils/Files.cpp.o
.PHONY : src/utils/Files.cpp.o

src/utils/Files.i: src/utils/Files.cpp.i
.PHONY : src/utils/Files.i

# target to preprocess a source file
src/utils/Files.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/utils/Files.cpp.i
.PHONY : src/utils/Files.cpp.i

src/utils/Files.s: src/utils/Files.cpp.s
.PHONY : src/utils/Files.s

# target to generate assembly for a file
src/utils/Files.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/utils/Files.cpp.s
.PHONY : src/utils/Files.cpp.s

src/utils/Random.o: src/utils/Random.cpp.o
.PHONY : src/utils/Random.o

# target to build an object file
src/utils/Random.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/utils/Random.cpp.o
.PHONY : src/utils/Random.cpp.o

src/utils/Random.i: src/utils/Random.cpp.i
.PHONY : src/utils/Random.i

# target to preprocess a source file
src/utils/Random.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/utils/Random.cpp.i
.PHONY : src/utils/Random.cpp.i

src/utils/Random.s: src/utils/Random.cpp.s
.PHONY : src/utils/Random.s

# target to generate assembly for a file
src/utils/Random.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnoptGenCore.dir/build.make CMakeFiles/UnoptGenCore.dir/src/utils/Random.cpp.s
.PHONY : src/utils/Random.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RISCVTargetParserTableGen"
	@echo "... acc_gen"
	@echo "... intrinsics_gen"
	@echo "... omp_gen"
	@echo "... UnoptGenCore"
	@echo "... deoptgen"
	@echo "... mo-diff"
	@echo "... mochecker"
	@echo "... moclassify"
	@echo "... src/indicators/DiffChecker.o"
	@echo "... src/indicators/DiffChecker.i"
	@echo "... src/indicators/DiffChecker.s"
	@echo "... src/indicators/InlineIndicator.o"
	@echo "... src/indicators/InlineIndicator.i"
	@echo "... src/indicators/InlineIndicator.s"
	@echo "... src/indicators/InstCountIndicator.o"
	@echo "... src/indicators/InstCountIndicator.i"
	@echo "... src/indicators/InstCountIndicator.s"
	@echo "... src/indicators/LoopIndicator.o"
	@echo "... src/indicators/LoopIndicator.i"
	@echo "... src/indicators/LoopIndicator.s"
	@echo "... src/indicators/StaticProfileIndicator.o"
	@echo "... src/indicators/StaticProfileIndicator.i"
	@echo "... src/indicators/StaticProfileIndicator.s"
	@echo "... src/indicators/UBChecker.o"
	@echo "... src/indicators/UBChecker.i"
	@echo "... src/indicators/UBChecker.s"
	@echo "... src/transforms/CFGExpand/CFGExpand.o"
	@echo "... src/transforms/CFGExpand/CFGExpand.i"
	@echo "... src/transforms/CFGExpand/CFGExpand.s"
	@echo "... src/transforms/CFGExpand/CFGExpander.o"
	@echo "... src/transforms/CFGExpand/CFGExpander.i"
	@echo "... src/transforms/CFGExpand/CFGExpander.s"
	@echo "... src/transforms/CFGRandomSimplify/CFGRandomSimplify.o"
	@echo "... src/transforms/CFGRandomSimplify/CFGRandomSimplify.i"
	@echo "... src/transforms/CFGRandomSimplify/CFGRandomSimplify.s"
	@echo "... src/transforms/ExprExpand/AddSubExpand.o"
	@echo "... src/transforms/ExprExpand/AddSubExpand.i"
	@echo "... src/transforms/ExprExpand/AddSubExpand.s"
	@echo "... src/transforms/ExprExpand/BitwiseExpand.o"
	@echo "... src/transforms/ExprExpand/BitwiseExpand.i"
	@echo "... src/transforms/ExprExpand/BitwiseExpand.s"
	@echo "... src/transforms/ExprExpand/ExprExpandPass.o"
	@echo "... src/transforms/ExprExpand/ExprExpandPass.i"
	@echo "... src/transforms/ExprExpand/ExprExpandPass.s"
	@echo "... src/transforms/ExprExpand/ExprExpander.o"
	@echo "... src/transforms/ExprExpand/ExprExpander.i"
	@echo "... src/transforms/ExprExpand/ExprExpander.s"
	@echo "... src/transforms/ExprExpand/ICmpExpander.o"
	@echo "... src/transforms/ExprExpand/ICmpExpander.i"
	@echo "... src/transforms/ExprExpand/ICmpExpander.s"
	@echo "... src/transforms/ExprExpand/InstExpander.o"
	@echo "... src/transforms/ExprExpand/InstExpander.i"
	@echo "... src/transforms/ExprExpand/InstExpander.s"
	@echo "... src/transforms/ExprExpand/MulDivRemExpander.o"
	@echo "... src/transforms/ExprExpand/MulDivRemExpander.i"
	@echo "... src/transforms/ExprExpand/MulDivRemExpander.s"
	@echo "... src/transforms/ExprExpand/ShiftExpand.o"
	@echo "... src/transforms/ExprExpand/ShiftExpand.i"
	@echo "... src/transforms/ExprExpand/ShiftExpand.s"
	@echo "... src/transforms/InstRandomCombine/InstRandomCombine.o"
	@echo "... src/transforms/InstRandomCombine/InstRandomCombine.i"
	@echo "... src/transforms/InstRandomCombine/InstRandomCombine.s"
	@echo "... src/transforms/RandomCVP/RandomCVP.o"
	@echo "... src/transforms/RandomCVP/RandomCVP.i"
	@echo "... src/transforms/RandomCVP/RandomCVP.s"
	@echo "... src/transforms/RandomDSE/RandomDSE.o"
	@echo "... src/transforms/RandomDSE/RandomDSE.i"
	@echo "... src/transforms/RandomDSE/RandomDSE.s"
	@echo "... src/transforms/RandomLICM/RandomLICM.o"
	@echo "... src/transforms/RandomLICM/RandomLICM.i"
	@echo "... src/transforms/RandomLICM/RandomLICM.s"
	@echo "... src/transforms/RandomLoopSink/RandomLoopSink.o"
	@echo "... src/transforms/RandomLoopSink/RandomLoopSink.i"
	@echo "... src/transforms/RandomLoopSink/RandomLoopSink.s"
	@echo "... src/transforms/RandomMem2Reg/RandomMem2Reg.o"
	@echo "... src/transforms/RandomMem2Reg/RandomMem2Reg.i"
	@echo "... src/transforms/RandomMem2Reg/RandomMem2Reg.s"
	@echo "... src/transforms/RandomReg2Mem/RandomReg2Mem.o"
	@echo "... src/transforms/RandomReg2Mem/RandomReg2Mem.i"
	@echo "... src/transforms/RandomReg2Mem/RandomReg2Mem.s"
	@echo "... src/transforms/RandomScalarizer/RandomScalarizer.o"
	@echo "... src/transforms/RandomScalarizer/RandomScalarizer.i"
	@echo "... src/transforms/RandomScalarizer/RandomScalarizer.s"
	@echo "... src/transforms/RandomSink/RandomSink.o"
	@echo "... src/transforms/RandomSink/RandomSink.i"
	@echo "... src/transforms/RandomSink/RandomSink.s"
	@echo "... src/utils/Debug.o"
	@echo "... src/utils/Debug.i"
	@echo "... src/utils/Debug.s"
	@echo "... src/utils/Files.o"
	@echo "... src/utils/Files.i"
	@echo "... src/utils/Files.s"
	@echo "... src/utils/Random.o"
	@echo "... src/utils/Random.i"
	@echo "... src/utils/Random.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

